#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rubyzip
Version  : 1.2.0
Release  : 7
URL      : https://rubygems.org/downloads/rubyzip-1.2.0.gem
Source0  : https://rubygems.org/downloads/rubyzip-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks

%description
# rubyzip
[![Gem Version](https://badge.fury.io/rb/rubyzip.svg)](http://badge.fury.io/rb/rubyzip)
[![Build Status](https://secure.travis-ci.org/rubyzip/rubyzip.svg)](http://travis-ci.org/rubyzip/rubyzip)
[![Code Climate](https://codeclimate.com/github/rubyzip/rubyzip.svg)](https://codeclimate.com/github/rubyzip/rubyzip)
[![Coverage Status](https://img.shields.io/coveralls/rubyzip/rubyzip.svg)](https://coveralls.io/r/rubyzip/rubyzip?branch=master)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rubyzip-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-rubyzip.gemspec

%build
gem build rubygem-rubyzip.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rubyzip-1.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rubyzip-1.2.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/TODO
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/central_directory.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/compressor.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/constants.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/crypto/encryption.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/crypto/null_encryption.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/crypto/traditional_encryption.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/decompressor.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/deflater.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/dos_time.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/entry.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/entry_set.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/extra_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/extra_field/generic.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/extra_field/ntfs.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/extra_field/old_unix.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/extra_field/universal_time.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/extra_field/unix.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/extra_field/zip64.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/extra_field/zip64_placeholder.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/file.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/filesystem.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/inflater.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/input_stream.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/ioextras.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/ioextras/abstract_input_stream.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/ioextras/abstract_output_stream.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/null_compressor.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/null_decompressor.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/null_input_stream.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/output_stream.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/pass_thru_compressor.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/pass_thru_decompressor.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/streamable_directory.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/streamable_stream.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/samples/example.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/samples/example_filesystem.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/samples/example_recursive.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/samples/gtk_ruby_zip.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/samples/qtzip.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/samples/write_simple.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/samples/zipfind.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/basic_zip_file_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/case_sensitivity_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/central_directory_entry_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/central_directory_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/crypto/null_encryption_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/crypto/traditional_encryption_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/WarnInvalidDate.zip
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/file1.txt
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/file1.txt.deflatedData
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/file2.txt
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/globTest.zip
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/globTest/foo.txt
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/globTest/foo/bar/baz/foo.txt
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/globTest/food.txt
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/mimetype
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/notzippedruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/ntfs.zip
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/oddExtraField.zip
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/rubycode.zip
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/rubycode2.zip
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/test.xls
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/testDirectory.bin
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/zip64-sample.zip
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/zipWithDirs.zip
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/data/zipWithEncryption.zip
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/deflater_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/encryption_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/entry_set_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/entry_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/errors_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/extra_field_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/file_extract_directory_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/file_extract_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/file_permissions_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/file_split_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/file_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/filesystem/dir_iterator_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/filesystem/directory_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/filesystem/file_mutating_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/filesystem/file_nonmutating_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/filesystem/file_stat_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/gentestfiles.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/inflater_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/input_stream_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/ioextras/abstract_input_stream_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/ioextras/abstract_output_stream_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/ioextras/fake_io_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/local_entry_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/output_stream_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/pass_thru_compressor_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/pass_thru_decompressor_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/samples/example_recursive_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/settings_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/unicode_file_names_and_comments_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/zip64_full_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubyzip-1.2.0/test/zip64_support_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/rubyzip-1.2.0.gemspec
